name: emeraldchat_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_easyloading: ^3.0.5
  flutter_chat_ui: ^1.6.3
  shared_preferences: ^2.0.15
  http: 0.13.4
  camera: 0.10.0
  webview_flutter_plus: 0.3.0+2
  flutter_webrtc: 0.9.3
  web_socket_channel: ^2.2.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
    - assets/images/
    - assets/webpages/
    - assets/sample_json/
  uses-material-design: true

